Feature/webform pdfextration
edu-look/look-api pull request #20
Opened 2024-01-21 22:52 UTC by YtaloSauham

Realizar a review.

2024-01-23 03:18 UTC, danroxha requested changes

2024-01-23 03:18 UTC, danroxha commented on src/main/java/com/github/edulook/look/endpoint/CourseEndpoint.java
> +    }
Remover esse metodo

2024-01-23 03:18 UTC, danroxha commented on src/main/java/com/github/edulook/look/endpoint/CourseEndpoint.java
> +       // publisher.publishEvent(event);
Remover comentário

2024-01-23 03:18 UTC, danroxha commented on src/main/java/com/github/edulook/look/infra/config/security/filters/UserAuthenticatedAdapterFilter.java
> +
Remover linha em vazia

2024-01-23 03:18 UTC, danroxha commented on src/main/java/com/github/edulook/look/infra/worker/cron/RefreshTokenSchedule.java
> +
Remover comentário esse código

2024-01-23 03:18 UTC, danroxha commented on src/main/java/com/github/edulook/look/infra/worker/cron/RefreshTokenSchedule.java
> +*/
Remover comentário esse código

2024-01-23 03:18 UTC, danroxha commented on src/main/resources/templates/edit.html
> +                            <div>{{ item.option.enableOCR ? 'OCR Ativado' : 'Ativar OCR' }}</div>
Trocar ```OCR Ativado``` e ``` Ativar ORC```  por ```Sim``` ou ```Não```

2024-01-23 03:18 UTC, danroxha commented on src/main/resources/templates/edit.html
> +                                Ative o OCR caso seu PDF seja um scanner de outro documento.
Alterar ```Ative o OCR caso seu PDF seja um scanner de outro documento.``` por uma pergunta: ```O documento é um escaner/foto de um livro ou de outro material?```

2024-01-23 03:18 UTC, danroxha commented on src/main/resources/templates/edit.html
> +            <a class="custom-button button-add-forms" @click=areInputsValid()>Adicionar acessibilidade</a>
Alterar ```Adicionar acessibilidade``` para ```Finalizar adaptação de contéudo```

2024-01-23 03:18 UTC, danroxha commented on src/main/resources/templates/edit.html
> +                let varTeste = JSON.stringify(this.material)
Renomear variavel para o contexto correto

2024-01-23 03:18 UTC, danroxha commented on src/main/resources/templates/edit.html
>          background-image: url('data:image/svg+xml,<svg width="1440" height="1036" viewBox="0 0 1440 1036" fill="none" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><re
Porque do imagem em base64?

2024-01-23 03:46 UTC, danroxha commented on src/main/resources/templates/edit.html
> +                                Ative o OCR caso seu PDF seja um scanner de outro documento.
A resposta do sim ou não: https://github.com/edu-look/look-api/pull/20#discussion_r1462674720

2024-01-23 23:40 UTC, YtaloSauham commented on src/main/resources/templates/edit.html
>          background-image: url('data:image/svg+xml,<svg width="1440" height="1036" viewBox="0 0 1440 1036" fill="none" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><re
Tive dificuldade em referenciar imagens usando o inteli e spring. Dessa forma, consigo o mesmo resultado.

2024-01-24 23:46 UTC, danroxha approved these changes

2024-01-24 23:48 UTC, merged